name: Action Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get node version
        run: |
          echo "name=PROJECT_NODE_VERSION=$(cat $GITHUB_WORKSPACE/.nvmrc)" >> $GITHUB_ENV

      - name: Setup Node.js version ${{ env.PROJECT_NODE_VERSION }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ env.PROJECT_NODE_VERSION }}

      - name: Install dependencies and compile code
        run: |
          yarn install
          yarn build

      - name: Run tests
        run: |
          yarn test
